query getJobs($country: String, $locale: String,
  $keyword: String, $createdAt: String, $jobFunctions: [Int],
  $categories: [String], $locations: [Int], $careerLevels: [Int],
  $minSalary: Int, $maxSalary: Int, $salaryType: Int,
  $candidateSalary: Int, $candidateSalaryCurrency: String,
  $datePosted: Int, $jobTypes: [Int], $workTypes: [String],
  $industries: [Int], $page: Int, $pageSize: Int, $companyId: String,
  $advertiserId: String, $userAgent: String, $accNums: Int,
  $subAccount: Int, $minEdu: Int, $maxEdu: Int, $edus: [Int],
  $minExp: Int, $maxExp: Int, $seo: String, $searchFields: String,
  $candidateId: ID, $isDesktop: Boolean, $isCompanySearch: Boolean,
  $sort: String, $sVi: String, $duplicates: String, $flight: String,
  $solVisitorId: String) {
    jobs(
      country: $country
      locale: $locale
      keyword: $keyword
      createdAt: $createdAt
      jobFunctions: $jobFunctions
      categories: $categories
      locations: $locations
      careerLevels: $careerLevels
      minSalary: $minSalary
      maxSalary: $maxSalary
      salaryType: $salaryType
      candidateSalary: $candidateSalary
      candidateSalaryCurrency: $candidateSalaryCurrency
      datePosted: $datePosted
      jobTypes: $jobTypes
      workTypes: $workTypes
      industries: $industries
      page: $page
      pageSize: $pageSize
      companyId: $companyId
      advertiserId: $advertiserId
      userAgent: $userAgent
      accNums: $accNums
      subAccount: $subAccount
      minEdu: $minEdu
      edus: $edus
      maxEdu: $maxEdu
      minExp: $minExp
      maxExp: $maxExp
      seo: $seo
      searchFields: $searchFields
      candidateId: $candidateId
      isDesktop: $isDesktop
      isCompanySearch: $isCompanySearch
      sort: $sort
      sVi: $sVi
      duplicates: $duplicates
      flight: $flight
      solVisitorId: $solVisitorId
    ) {
      relatedSearchKeywords {
        keywords
      }
      jobs {
        job_id: id
        company: companyMeta {
          id
          name
        }
        job_title: jobTitle
        employment: employmentTypes {
          type: name
        }
        city: locations {
          name
        }
        category: categories {
          id: code
          name
        }
        salary: salaryRange {
          max
          min
          currency
          period
        }
        posted_at: postedAt
      }
    }
  }
